block_size: 134
desc_only: false
itos:
  0: '!'
  1: '#'
  2: (
  3: )
  4: '-'
  5: .
  6: /
  7: '1'
  8: '2'
  9: '3'
  10: '4'
  11: '5'
  12: '6'
  13: '7'
  14: '8'
  15: '9'
  16: <
  17: '='
  18: B
  19: Br
  20: C
  21: Cl
  22: F
  23: I
  24: N
  25: O
  26: P
  27: S
  28: '[2H]'
  29: '[B-]'
  30: '[Br-]'
  31: '[C-]'
  32: '[C@@H]'
  33: '[C@@]'
  34: '[C@H]'
  35: '[C@]'
  36: '[Cl-]'
  37: '[H]'
  38: '[I-]'
  39: '[K+]'
  40: '[N+]'
  41: '[N-]'
  42: '[NH+]'
  43: '[NH3+]'
  44: '[Na+]'
  45: '[O-]'
  46: '[P+]'
  47: '[S+]'
  48: '[S@@]'
  49: '[Se]'
  50: '[Si]'
  51: '[n+]'
  52: '[nH]'
  53: '[se]'
  54: \
  55: c
  56: n
  57: o
  58: s
  59: '~'
len_data: 277677
stoi:
  '!': 0
  '#': 1
  (: 2
  ): 3
  '-': 4
  .: 5
  /: 6
  '1': 7
  '2': 8
  '3': 9
  '4': 10
  '5': 11
  '6': 12
  '7': 13
  '8': 14
  '9': 15
  <: 16
  '=': 17
  B: 18
  Br: 19
  C: 20
  Cl: 21
  F: 22
  I: 23
  N: 24
  O: 25
  P: 26
  S: 27
  '[2H]': 28
  '[B-]': 29
  '[Br-]': 30
  '[C-]': 31
  '[C@@H]': 32
  '[C@@]': 33
  '[C@H]': 34
  '[C@]': 35
  '[Cl-]': 36
  '[H]': 37
  '[I-]': 38
  '[K+]': 39
  '[N+]': 40
  '[N-]': 41
  '[NH+]': 42
  '[NH3+]': 43
  '[Na+]': 44
  '[O-]': 45
  '[P+]': 46
  '[S+]': 47
  '[S@@]': 48
  '[Se]': 49
  '[Si]': 50
  '[n+]': 51
  '[nH]': 52
  '[se]': 53
  \: 54
  c: 55
  n: 56
  o: 57
  s: 58
  '~': 59
vocab_size: 60
