block_size: 134
desc_only: false
itos:
  0: '!'
  1: '#'
  2: (
  3: )
  4: '-'
  5: .
  6: /
  7: '1'
  8: '2'
  9: '3'
  10: '4'
  11: '5'
  12: '6'
  13: '7'
  14: '8'
  15: '9'
  16: <
  17: '='
  18: B
  19: Br
  20: C
  21: Cl
  22: F
  23: I
  24: N
  25: O
  26: P
  27: S
  28: '[Br-]'
  29: '[C-]'
  30: '[C@@H]'
  31: '[C@@]'
  32: '[C@H]'
  33: '[C@]'
  34: '[Cl-]'
  35: '[H]'
  36: '[I-]'
  37: '[N+]'
  38: '[N-]'
  39: '[NH+]'
  40: '[NH3+]'
  41: '[Na+]'
  42: '[O-]'
  43: '[P+]'
  44: '[S+]'
  45: '[S@@]'
  46: '[Se]'
  47: '[Si]'
  48: '[n+]'
  49: '[nH]'
  50: '[se]'
  51: \
  52: c
  53: n
  54: o
  55: s
  56: '~'
len_data: 277548
stoi:
  '!': 0
  '#': 1
  (: 2
  ): 3
  '-': 4
  .: 5
  /: 6
  '1': 7
  '2': 8
  '3': 9
  '4': 10
  '5': 11
  '6': 12
  '7': 13
  '8': 14
  '9': 15
  <: 16
  '=': 17
  B: 18
  Br: 19
  C: 20
  Cl: 21
  F: 22
  I: 23
  N: 24
  O: 25
  P: 26
  S: 27
  '[Br-]': 28
  '[C-]': 29
  '[C@@H]': 30
  '[C@@]': 31
  '[C@H]': 32
  '[C@]': 33
  '[Cl-]': 34
  '[H]': 35
  '[I-]': 36
  '[N+]': 37
  '[N-]': 38
  '[NH+]': 39
  '[NH3+]': 40
  '[Na+]': 41
  '[O-]': 42
  '[P+]': 43
  '[S+]': 44
  '[S@@]': 45
  '[Se]': 46
  '[Si]': 47
  '[n+]': 48
  '[nH]': 49
  '[se]': 50
  \: 51
  c: 52
  n: 53
  o: 54
  s: 55
  '~': 56
vocab_size: 57
